### ISSUE TITLE
txt file schemas

### ISSUE THREAD

**Issue by jasonwiener** [wltribble/Fitness-Calculator#1]
Hi. Interested in using this as well. 

Not sure of the data.txt schema.  As well, there is no sample of the fitNums.txt. Would be great to know where that data is coming from, and the schema the script expects.

**Comment by wltribble** [comment]
Hey man, lemme get on that this weekend! Sorry it was vague, I had no idea anyone would ever even look at this stuff. I was just posting it here to show my friends haha!

**Comment by wltribble** [comment]
I uploaded a sample fitNums.txt and updated the readme to better describe what's going on here. Lemme know if you have any questions! You can also email me at wltribble@gmail.com if you need anything else
